# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170607_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_by',
        ),
    ]
